#!/bin/bash

# This script is used to zip the source code of the project.

sources=(
  "assets"
  "COPYING"
  "jest.config.js"
  "LICENSE_TEMPLATE"
  "manifest.chrome.json"
  "manifest.firefox.json"
  "package.json"
  "pnpm-lock.yaml"
  "README.md"
  "rollup.config.mjs"
  "scripts"
  "src"
  "tsconfig.json"
  "typings"
)

zip -r sources.zip ${sources[@]}
