name: CI-CD

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow semantic release
permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Test
        run: pnpm test

  version:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Release
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish:
    runs-on: ubuntu-latest
    needs: [test, version]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build:prod

      - name: Create zip's
        run: |
          (cd build-chrome && zip chrome-extension.zip ./*)
          (cd build-firefox && zip firefox-extension.zip ./*)
          ./scripts/zip-source src

      - name: Tree
        run: |
          ls -la
          ls -laR build*

      - name: Publish
        run: |
          npx publish-browser-extension \
            --dry-run \
            --chrome-zip "build-chrome/chrome-extension.zip" \
            --chrome-extension-id "lfnnlbomdeeijpmgigmkkdemhpjelikg" \
            --chrome-client-id "${{ secrets.CHROME_CLIENT_ID }}" \
            --chrome-client-secret "${{ secrets.CHROME_CLIENT_SECRET }}" \
            --chrome-refresh-token "${{ secrets.CHROME_REFRESH_TOKEN }}" \
            --chrome-publish-target "default" \
            --chrome-skip-submit-review \
            --firefox-zip "build-firefox/firefox-extension.zip" \
            --firefox-sources-zip "sources.zip" \
            --firefox-extension-id "prun-palette@prun-palette" \
            --firefox-jwt-issuer "${{ secrets.FIREFOX_JWT_ISSUER }}" \
            --firefox-jwt-secret "${{ secrets.FIREFOX_JWT_SECRET }}" \
            --firefox-channel "listed" \
